// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Person/pkg/models/shared"
	"net/http"
)

type FindPersonRequest struct {
	// The name of the company the person works for
	Company *string `queryParam:"style=form,explode=true,name=company"`
	// The domain of the company the person works for
	CompanyDomain *string `queryParam:"style=form,explode=true,name=company_domain"`
	// The email address to look up
	Email string `queryParam:"style=form,explode=true,name=email"`
	// The person's Facebook profile URL
	Facebook *string `queryParam:"style=form,explode=true,name=facebook"`
	// The person's last name. If you have this, passing this is strongly recommended to improve match rates
	FamilyName *string `queryParam:"style=form,explode=true,name=family_name"`
	// The person's first name
	GivenName *string `queryParam:"style=form,explode=true,name=given_name"`
	// The person's IP address. If you have this, passing this is strongly recommended to improve match rates
	IPAddress *string `queryParam:"style=form,explode=true,name=ip_address"`
	// The person's LinkedIn profile URL
	Linkedin *string `queryParam:"style=form,explode=true,name=linkedin"`
	// The city or country where the person lives
	Location *string `queryParam:"style=form,explode=true,name=location"`
	// The person's Twitter profile username
	Twitter *string `queryParam:"style=form,explode=true,name=twitter"`
	// A webhook URL that results will be sent to
	WebhookURL *string `queryParam:"style=form,explode=true,name=webhook_url"`
}

type FindPersonResponse struct {
	ContentType string
	// Successful lookup, person encoded in the response body
	Person      *shared.Person
	StatusCode  int
	RawResponse *http.Response
}
